version: '3.1' #docker-compose syntax version

services:
  short-url:
    build: . #build current directory
    image: "wkas/short-url:${TAG}"
    container_name: short-url
    env_file:
      - secrets.env
    environment:
      ADDRESS: ":443"
    ports:
      - 443:443
