version: '3.1' #docker-compose syntax version

services:
  short-url-nginx: 
    image: nginx:latest
    container_name: short-url-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    links:
      - short-url
      - short-url-frontend

  short-url:
    image: ${IMAGE_NAME}:${TAG}
    container_name: ${CONTAINER_NAME}
    env_file:
      - secrets.env
    environment:
      ADDRESS: ":8080"
      ADDRESS_TLS: ":4430"
      PROD: "1"
    ports:
      - 8080:8080
      - 4430:4430

  short-url-frontend:
    image: wkas/short-url-frontend:1.0.0
    container_name: short-url-frontend
    ports:
      - 8081:8081
