version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.12
      - image: "circleci/mongo:3.6.0"

    environment:
      TEST_RESULTS: /tmp/test-results
      GO111MODULE: "on"

    working_directory: /go/src/github.com/w-k-s/short-url
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS

      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}

      - run: go get
      - run: go get github.com/jstemmer/go-junit-report

      - run:
          name: Run unit tests
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            make test | tee ${TEST_RESULTS}/go-test.out

      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results
  
  deploy:
    docker:
      - image: circleci/golang:1.12
    environment:
      GO111MODULE: "on"
    working_directory: /go/src/github.com/w-k-s/short-url
    steps:
      - checkout
      - run: go get
      - setup_remote_docker # https://circleci.com/docs/2.0/building-docker-images/
      - run:
          name: Login to docker hub
          command: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - run:
          name: docker build image
          command: docker build -t "wkas/short-url:$CIRCLE_BUILD_NUM" .
      - run:
          name: docker push image
          command: docker push "wkas/short-url:$CIRCLE_BUILD_NUM"
      # `-o StrictHostKeyChecking=no` disables 'The authenticity of host ? can't be established confirmation'
      - run:
          name: Secure copy docker-compose.production.yml
          command: scp -o StrictHostKeyChecking=no docker-compose.production.yml ec2-user@small.ml:~/
      - run:
          name: Secure copy Makefile
          command: scp -o StrictHostKeyChecking=no Makefile ec2-user@small.ml:~/
      - run:
          name: Secure copy nginx.conf
          command: scp -o StrictHostKeyChecking=no nginx.conf ec2-user@small.ml:~/
      - run:
          name: Generate .env file
          command: sh ./env.sh && scp -o StrictHostKeyChecking=no .env ec2-user@small.ml:~/
      - run:
          name: Up!
          command: ssh -o StrictHostKeyChecking=no ec2-user@small.ml "make docker-restart-prod"

workflows:
  version: 2
  deployment:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master