version: '3.1' #docker-compose syntax version

services:
  short-url-nginx: 
    image: nginx:latest
    container_name: short-url-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/shortest.ml/fullchain.pem:/etc/letsencrypt/live/shortest.ml/fullchain.pem
      - /etc/letsencrypt/live/shortest.ml/privkey.pem:/etc/letsencrypt/live/shortest.ml/privkey.pem
    ports:
      - 80:80
      - 443:443
    links:
      - short-url
      - short-url-frontend

  short-url:
    image: wkas/short-url:prod
    container_name: short-url
    restart: always
    env_file:
      - .env
    environment:
      ADDRESS: ":8080"
      PROD: "1"
    ports:
      - 8080:8080
      - 4430:4430
