version: '2.1' #docker-compose syntax version

services:
  short-url-nginx: 
    image: nginx:latest
    container_name: short-url-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    links:
      - short-url
      - short-url-frontend
  
  short-url-frontend:
    image: wkas/short-url-frontend:dev
    container_name: short-url-frontend
    ports:
      - 8081:8081
  
  short-url:
    image: wkas/short-url:dev
    container_name: short-url
    restart: always
    environment:
      ADDRESS: ":8080"
      DB_CONN_STRING: "postgres://shorturl:password@datastore:5432/url_shortener?sslmode=disable"
    ports:
      - 8080:8080
      - 4430:4430
    links:
      - datastore
    depends_on:
      datastore:
        condition: service_healthy
  
  datastore: #https://docs.docker.com/compose/networking/
    image: mdillon/postgis
    restart: always
    container_name: short-url-datastore
    environment:
      POSTGRES_USER: shorturl
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url_shortener
    ports:
      - 5432:5432
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  data: {}